app_front_category:
    resource: "@AppFrontBundle/Resources/config/routing/category.yml"
    prefix:   /category

app_front_livre:
    resource: "@AppFrontBundle/Resources/config/routing/livre.yml"
    prefix:   /livre

app_contact:
    path:     /nous-contacter
    defaults: { _controller: AppFrontBundle:Default:contact}

app_homepage:
    path:     /
    defaults: { _controller: AppFrontBundle:Default:index }

